In [1]:
# oltp and olap 2. database and warehouse difference

In [1]:
import numpy as np

In [4]:
arr = np.array(range(25))

In [5]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
arr = np.array(range(24))

In [10]:
arr = arr.reshape(2,3,4)

In [11]:
arr.ndim

3

In [12]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Arange genrates a array with numbers in a range

In [15]:
arr = np.arange(2, 24, 3)

In [14]:
# jitne input denge utni dimension bdegi

In [16]:
arr.reshape(-1)

array([ 2,  5,  8, 11, 14, 17, 20, 23])

### genrates numbers linearly spaced from starting index including index

In [18]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### random functions

#### genrates array random numbers from uniform distribution between 0 and 1

In [19]:
np.random.rand(5)

array([0.73851724, 0.07628979, 0.74095887, 0.81559533, 0.64392708])

In [20]:
np.random.rand(5,3)

array([[0.53783623, 0.65238797, 0.93340512],
       [0.93248489, 0.70690851, 0.80499733],
       [0.27891905, 0.76589553, 0.36776875],
       [0.22026568, 0.52624473, 0.86201434],
       [0.56351052, 0.77967888, 0.94882043]])

### normal distribution with center as 0

In [24]:
np.random.randn(5)

array([-0.06001478, -2.26312732,  0.12944542, -1.99657343,  0.26553655])

In [25]:
np.random.randn(5,5)

array([[-0.08722481,  0.42281719,  0.12548047, -0.14444209, -1.02982839],
       [-0.51062681,  0.95540411, -0.08183409,  0.63294128, -1.45048288],
       [-0.94308747, -0.04354084,  1.37357667, -0.79067123, -0.04869746],
       [ 1.79609832, -0.37007384, -0.55168274,  0.00976054,  0.76564527],
       [ 0.27374724, -0.40054657,  0.32757859, -0.30042469,  0.80256166]])

### genrates array of random numbers between starting and ending

In [40]:
arr = np.random.randint(0,50, (3,6)) # 2,2 is used for array 2 rows 2 columns

In [41]:
arr

array([[48, 37, 23,  0, 24, 29],
       [11, 17, 43, 10, 13, 48],
       [11,  1, 19, 12, 18, 37]], dtype=int32)

In [42]:
arr.reshape(-1)

array([48, 37, 23,  0, 24, 29, 11, 17, 43, 10, 13, 48, 11,  1, 19, 12, 18,
       37], dtype=int32)

In [44]:
arr.flatten()

array([48, 37, 23,  0, 24, 29, 11, 17, 43, 10, 13, 48, 11,  1, 19, 12, 18,
       37], dtype=int32)

In [45]:
arr.flatten(order = 'F')

array([48, 11, 11, 37, 17,  1, 23, 43, 19,  0, 10, 12, 24, 13, 18, 29, 48,
       37], dtype=int32)

In [46]:
help(arr.flatten)

Help on built-in function flatten:

flatten(...) method of numpy.ndarray instance
    a.flatten(order='C')

    Return a copy of the array collapsed into one dimension.

    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        'C' means to flatten in row-major (C-style) order.
        'F' means to flatten in column-major (Fortran-
        style) order. 'A' means to flatten in column-major
        order if `a` is Fortran *contiguous* in memory,
        row-major order otherwise. 'K' means to flatten
        `a` in the order the elements occur in memory.
        The default is 'C'.

    Returns
    -------
    y : ndarray
        A copy of the input array, flattened to one dimension.

    See Also
    --------
    ravel : Return a flattened array.
    flat : A 1-D flat iterator over the array.

    Examples
    --------
    >>> import numpy as np
    >>> a = np.array([[1,2], [3,4]])
    >>> a.flatten()
    array([1, 2, 3, 4])
    >>> a.flatten('F')
    array([1, 3

In [49]:
arr.flatten(order= 'a')

array([48, 37, 23,  0, 24, 29, 11, 17, 43, 10, 13, 48, 11,  1, 19, 12, 18,
       37], dtype=int32)

In [50]:
arr.flatten(order= 'A')

array([48, 37, 23,  0, 24, 29, 11, 17, 43, 10, 13, 48, 11,  1, 19, 12, 18,
       37], dtype=int32)

In [51]:
arr.flatten(order= 'K')

array([48, 37, 23,  0, 24, 29, 11, 17, 43, 10, 13, 48, 11,  1, 19, 12, 18,
       37], dtype=int32)

In [52]:
arr

array([[48, 37, 23,  0, 24, 29],
       [11, 17, 43, 10, 13, 48],
       [11,  1, 19, 12, 18, 37]], dtype=int32)

### Matrix arrangement of data in reactangular form

#### rectangular matrix

In [54]:
np.random.randint(0,100, (5,3))

array([[70, 29, 39],
       [73, 91, 77],
       [90, 89, 27],
       [88, 99, 50],
       [74, 56, 49]], dtype=int32)

#### Square matrix

In [55]:
np.random.randint(0,100, (3,3))

array([[57, 27, 32],
       [35, 62, 27],
       [81, 70, 61]], dtype=int32)

### Triangle matrix

#### Upper triangle matrix

In [59]:
np.array([
    [1,2,3],
    [0,5,6],
    [0,0,9]
])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

#### lower triangle matrix

In [58]:
np.array([
    [1,0,0],
    [2,3,0],
    [4,5,6]
])

array([[1, 0, 0],
       [2, 3, 0],
       [4, 5, 6]])

### diagonal matrix

In [60]:
np.array([
    [1,0,0],
    [0,2,0],
    [0,0,3]
])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Transpose of a matrix

In [63]:
arr = np.random.randint(0,100, (3,3))

In [64]:
arr.transpose()

array([[26, 16, 92],
       [49, 60,  4],
       [11, 65, 71]], dtype=int32)

In [65]:
arr

array([[26, 49, 11],
       [16, 60, 65],
       [92,  4, 71]], dtype=int32)

## identity matrix

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### One and Zero

In [4]:
zero = np.zeros((5,5))

In [5]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])