In [1]:
import numpy as np

In [2]:
np.random.seed(50)

In [4]:
arr = np.random.randint(1,20, (3,3))

In [5]:
arr

array([[14,  6,  3],
       [ 8, 16,  5],
       [15,  4,  7]], dtype=int32)

In [6]:
arr[2] # firstly we slice row according

array([15,  4,  7], dtype=int32)

In [8]:
arr[2][0]

np.int32(15)

In [10]:
arr[2,0] # we can also write this first row then column

np.int32(15)

In [25]:
arr1 = np.random.randint(1,20, (3,5, 4))

In [26]:
arr1

array([[[ 6,  7, 10,  5],
        [10,  1, 16, 17],
        [18, 17,  5, 12],
        [ 2,  6, 14,  4],
        [15,  3,  9,  7]],

       [[ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16],
        [ 4,  5, 10,  5],
        [ 8, 18, 14, 10]],

       [[15, 14, 16,  4],
        [ 7, 13, 11, 15],
        [ 1, 14, 14,  1],
        [ 9, 16, 14,  1],
        [11, 15, 13,  5]]], dtype=int32)

In [13]:
arr[1]

array([[12,  8, 15, 14],
       [ 8,  5,  5,  1],
       [12,  1, 14, 14],
       [ 2, 10, 12,  6],
       [ 1, 16,  6,  7]], dtype=int32)

In [14]:
arr[1,3]

array([ 2, 10, 12,  6], dtype=int32)

In [16]:
arr[1,3,2] # first represent row total rows second represent row then third represent column

np.int32(12)

## Slicing

In [17]:
arr = np.random.randint(1, 20, (5,5))

In [18]:
arr

array([[ 5, 19, 16, 11, 18],
       [ 9, 15, 12,  8, 10],
       [ 2,  9,  4,  4, 11],
       [ 4,  7, 16,  1, 19],
       [12,  2, 18, 15, 15]], dtype=int32)

In [19]:
arr[2:4]

array([[ 2,  9,  4,  4, 11],
       [ 4,  7, 16,  1, 19]], dtype=int32)

In [20]:
arr[2:4, 1:3]

array([[ 9,  4],
       [ 7, 16]], dtype=int32)

In [23]:
arr[3:]

array([[ 4,  7, 16,  1, 19],
       [12,  2, 18, 15, 15]], dtype=int32)

In [24]:
arr

array([[ 5, 19, 16, 11, 18],
       [ 9, 15, 12,  8, 10],
       [ 2,  9,  4,  4, 11],
       [ 4,  7, 16,  1, 19],
       [12,  2, 18, 15, 15]], dtype=int32)

In [27]:
arr1

array([[[ 6,  7, 10,  5],
        [10,  1, 16, 17],
        [18, 17,  5, 12],
        [ 2,  6, 14,  4],
        [15,  3,  9,  7]],

       [[ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16],
        [ 4,  5, 10,  5],
        [ 8, 18, 14, 10]],

       [[15, 14, 16,  4],
        [ 7, 13, 11, 15],
        [ 1, 14, 14,  1],
        [ 9, 16, 14,  1],
        [11, 15, 13,  5]]], dtype=int32)

In [29]:
arr1[:, 1:4, 1:3]

array([[[ 1, 16],
        [17,  5],
        [ 6, 14]],

       [[15,  5],
        [18, 15],
        [ 5, 10]],

       [[13, 11],
        [14, 14],
        [16, 14]]], dtype=int32)

In [30]:
arr1

array([[[ 6,  7, 10,  5],
        [10,  1, 16, 17],
        [18, 17,  5, 12],
        [ 2,  6, 14,  4],
        [15,  3,  9,  7]],

       [[ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16],
        [ 4,  5, 10,  5],
        [ 8, 18, 14, 10]],

       [[15, 14, 16,  4],
        [ 7, 13, 11, 15],
        [ 1, 14, 14,  1],
        [ 9, 16, 14,  1],
        [11, 15, 13,  5]]], dtype=int32)

In [35]:
arr1[1,3,2]

np.int32(10)

In [42]:
arr1[1:2, 1:3, 2:]

array([[[ 5, 12],
        [15, 16]]], dtype=int32)

In [43]:
arr = np.random.randint(1,10, (4,4))

In [44]:
arr

array([[9, 1, 8, 6],
       [5, 5, 8, 8],
       [1, 9, 8, 7],
       [8, 4, 6, 3]], dtype=int32)

In [46]:
arr[0, -1] = 0

In [47]:
arr

array([[9, 1, 8, 0],
       [5, 5, 8, 8],
       [1, 9, 8, 7],
       [8, 4, 6, 3]], dtype=int32)

In [50]:
arr[-1,2] = -10

In [51]:
arr

array([[  9,   1,   8,   0],
       [  5,   5,   8,   8],
       [  1,   9,   8,   7],
       [  8,   4, -10,   3]], dtype=int32)

In [52]:
arr[2:, 0:2] = 5

In [53]:
arr

array([[  9,   1,   8,   0],
       [  5,   5,   8,   8],
       [  5,   5,   8,   7],
       [  5,   5, -10,   3]], dtype=int32)

In [54]:
arr

array([[  9,   1,   8,   0],
       [  5,   5,   8,   8],
       [  5,   5,   8,   7],
       [  5,   5, -10,   3]], dtype=int32)

In [57]:
 a = arr[-2:, -2:]

In [58]:
a

array([[  8,   7],
       [-10,   3]], dtype=int32)

In [59]:
arr

array([[  9,   1,   8,   0],
       [  5,   5,   8,   8],
       [  5,   5,   8,   7],
       [  5,   5, -10,   3]], dtype=int32)

In [60]:
a[0, -1] = 100

In [61]:
a

array([[  8, 100],
       [-10,   3]], dtype=int32)

In [62]:
arr

array([[  9,   1,   8,   0],
       [  5,   5,   8,   8],
       [  5,   5,   8, 100],
       [  5,   5, -10,   3]], dtype=int32)

In [63]:
# if we do changes in copy then it doenot save in original array it create copy exa=.copy()

In [64]:
arr

array([[  9,   1,   8,   0],
       [  5,   5,   8,   8],
       [  5,   5,   8, 100],
       [  5,   5, -10,   3]], dtype=int32)

In [66]:
arr = np.arange(9)
arr = arr.reshape(3,3)

In [67]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
a = arr

In [69]:
b = arr.copy()

In [70]:
a[0][0] = 50

In [71]:
arr

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [72]:
b[0,0] = 100

In [73]:
b

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [74]:
arr

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])